---
title: "Testing P. entomophila indirect transmission"
subtitle: "Survival and Pe load in females infected with food used by lightly infected males"
date: ""
chunk_output_type: inline
output: html_document
theme: yeti
toc: yes
toc_float: yes
authors: "Youn"
---
  
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, message = FALSE, warning = FALSE)
```


# Packages

```{r packages-loading}
#[R v4.2.1]
if(require("pacman")==T){
  library("pacman")
}else{
  install.packages("pacman")
}

pacman::p_load(Rmisc, tidyverse, tidybayes, ggplot2, kableExtra, survival, survminer, performance, car, lme4, multcomp, emmeans, brms, cmdstanr, ggtext, relaimpo, gridExtra, DHARMa)

library(here)      # CRAN v1.0.1
## tool for workspace location management
## automatically detects the workspace after loading the package if Rstudio was opened using the script file
## load last to avoid conflicts
here::here()

```

# Preprocess

Loading the data

```{r data-load}
survival_data=read.table(here::here("data_survival_transmission.txt"),h=T, dec=".")
head(survival_data)

plating_data=read.table(here::here("data_plating_transmission.txt"),h=T, dec=".")
head(plating_data)

```

Editing data tables for cleaner graphical outputs

```{r data tinkering}
data_survival = survival_data %>%
  mutate(infection = str_replace_all(infection, "P_entomophila", "*P. entomophila*")) %>%
  mutate(infection =factor(infection, levels=c("sham", "*P. entomophila*"))) %>%
  mutate(food2 = str_replace_all(food, "T2", "-mp diet")) %>%
  arrange(infection) %>%
  arrange(food2)

data_survival_end=subset(data_survival, data_survival$time==148)

data_CFU = plating_data %>%
  mutate(infection2 = str_replace_all(infection, "P_entomophila", "*P. entomophila*")) %>%
  mutate(infection2 =factor(infection2, levels=c("sham", "*P. entomophila*"))) %>%
  mutate(food2 = str_replace_all(food, "T2", "-mp diet")) %>%
  arrange(infection) %>%
  arrange(food2)

data_CFU2=subset(data_CFU, data_CFU$infection=="P_entomophila")

mycol=c("#808080","#f01010")
mycol2=c("#f01010")

```

# Survival, Pe load, and their correlation

Plots

```{r survival and plating plot}
plot_survival <- ggplot(data_survival, aes(time/24, (alive_flies/total_flies)))
plot_survival <- plot_survival+
    geom_smooth(aes(group = infection, colour=infection, fill = infection), method = 'loess', size=0.8, linetype=1, alpha=0.2, position=position_dodge(0.2), show.legend = T, se = T, span = 1.5)+
  stat_summary(fun=mean, geom="point", aes(group = infection, colour=infection), size=2, alpha=1, position=position_dodge(0.2), show.legend = F)+
  scale_fill_manual(values=mycol)+
  scale_color_manual(values=mycol)+
  theme_bw(base_size = 12)+
  labs(x= "Days post-transfer", y="Proportion of alive flies")+
  coord_cartesian(ylim=c(0,1), xlim=c(0,7))+
  scale_x_continuous(breaks = c(0:7))+
  theme(strip.text.x = element_markdown(angle = 0), axis.text.x = element_text(angle=0, vjust=0.5, hjust=0.5), panel.grid.major.x = element_blank(), panel.grid.minor = element_blank(), legend.position = c(0.5, 0.2), legend.key.size = unit(0.2, "cm"), legend.background = element_blank(), legend.text = element_markdown())

plot_survival

###

plot_cfu=ggplot(aes(x=infection2, y=(CFU_per_fly+1), fill=infection2, colour=infection2), data=data_CFU)+
  geom_hline(yintercept=128000000, linetype='dotted', color = 'black')+
  geom_hline(yintercept=80, linetype='dotted', color = 'black')+
  geom_dotplot(shape=15, binaxis='y',binwidth = 0.15, stackdir='center', position=position_dodge(0.8), show.legend = F)+
  annotate("text", x = 0.65, y = 128000000, label = "max.", vjust = -0.3, size= 3)+
  annotate("text", x = 0.65, y = 80, label = "min.", vjust = -0.3, size= 3)+
  scale_fill_manual(values=mycol)+
  scale_color_manual(values=mycol)+
  labs(x= "Infection status", y="*P. entomophila* CFU/fly", fill ="Infection status")+
  coord_cartesian(ylim=c(1,200000000))+
  theme_bw(base_size = 12)+
  guides(colour="none")+
  scale_y_log10(breaks = c(10, 100, 1000, 10000, 100000, 1000000, 10000000, 100000000), labels=scales::scientific)+
  theme(panel.grid.major.x = element_blank(), panel.grid.minor = element_blank(), strip.background.y = element_blank(), strip.text.y = element_blank())+
  theme(axis.text.x = element_markdown(angle=0, vjust=0, hjust=0.5), axis.title.y = element_markdown(), legend.position = "right", legend.text = element_markdown())

plot_cfu

###

corCFU=cor.test(x=(1-(data_CFU2$alive_flies/data_CFU2$total_flies)), y=(data_CFU2$CFU_per_fly+1), method="pearson")

plot_regression=ggplot(aes(x=(1-(alive_flies/total_flies)), y=(CFU_per_fly+1), colour=infection2), data=data_CFU2)+
  geom_hline(yintercept=128000000, linetype='dotted', color = 'black')+
  geom_hline(yintercept=80, linetype='dotted', color = 'black')+
  annotate("text", x = 0.05, y = 128000000, label = "max.", vjust = -0.3, size= 3)+
  annotate("text", x = 0.05, y = 80, label = "min.", vjust = -0.3, size= 3)+
  annotate("text", x = 0.6, y = 80, label = "Pearson's coefficient = 0.71 \n p-value = 0.02", vjust = -0.3, size= 2)+
  geom_smooth(aes(group=1), method = 'lm', color="black", size=0.5, linetype=1, alpha=0.8, show.legend = F, se = FALSE)+
  geom_jitter(width = 0.02, height = 0.2, show.legend = F)+
  labs(x= "Proportion of dead flies", y="*P. entomophila* CFU/fly", colour ="Infection status")+
  scale_color_manual(values=mycol2)+
  coord_cartesian(ylim=c(1,200000000))+
  theme_bw(base_size = 12)+
  scale_y_log10(breaks = c(10, 100, 1000, 10000, 100000, 1000000, 10000000, 100000000), labels=scales::scientific)+
  theme(panel.grid.major.x = element_blank(), panel.grid.minor = element_blank(), strip.background.y = element_blank(), strip.text.y = element_blank())+
  theme(axis.text.x = element_text(angle=0, vjust=0, hjust=0.5), axis.title.y = element_markdown(), legend.position = "right", legend.text = element_markdown())


plot_regression

###

plot_survival = plot_survival+
  theme(panel.grid.major.x = element_blank(), panel.grid.major.y = element_line(color = "grey95", size = 0.4), panel.grid.minor = element_blank())+
  theme(axis.text.x = element_text(size = 8, angle=0, vjust=0, hjust=0.5), axis.text.y = element_text(size = 8), axis.title.x = element_markdown(size = 12, padding = margin(5, 0, 0, 0)), axis.title.y = element_markdown(size = 12), strip.text.x = element_blank(), strip.text.y = element_blank(),  strip.background.x = element_blank(), strip.background.y = element_blank(), legend.title = element_blank(), plot.margin = margin(t = 30, r = 22, b = 6, l = 6, unit = "pt"), panel.border = element_rect(colour = "grey20", fill=NA, size=0.4))

plot_cfu = plot_cfu+
  theme(panel.grid.major.x = element_blank(), panel.grid.major.y = element_line(color = "grey95", size = 0.4), panel.grid.minor = element_blank())+
  theme(axis.text.x = element_markdown(size = 8, angle=0, vjust=0, hjust=0.5), axis.text.y = element_markdown(size = 8), axis.title.x = element_markdown(size = 12, padding = margin(5, 0, 0, 0)), axis.title.y = element_markdown(size = 12), strip.text.x = element_blank(), strip.text.y = element_blank(),  strip.background.x = element_blank(), strip.background.y = element_blank(), legend.title = element_markdown(), plot.margin = margin(t = 30, r = 22, b = 6, l = 6, unit = "pt"), panel.border = element_rect(colour = "grey20", fill=NA, size=0.4))

plot_regression = plot_regression+
  theme(panel.grid.major.x = element_blank(), panel.grid.major.y = element_line(color = "grey95", size = 0.4), panel.grid.minor = element_blank())+
  theme(axis.text.x = element_markdown(size = 8, angle=0, vjust=0, hjust=0.5), axis.text.y = element_markdown(size = 8), axis.title.x = element_markdown(size = 12, padding = margin(5, 0, 0, 0)), axis.title.y = element_markdown(size = 12), strip.text.x = element_blank(), strip.text.y = element_blank(),  strip.background.x = element_blank(), strip.background.y = element_blank(), legend.title = element_markdown(), plot.margin = margin(t = 30, r = 22, b = 6, l = 6, unit = "pt"), panel.border = element_rect(colour = "grey20", fill=NA, size=0.4))

pdf(height=3, width=8, file=here::here("plot_summary.pdf"))
grid.arrange(plot_survival, plot_cfu, plot_regression, nrow = 1, widths = c(1, 1, 1))
dev.off()



```

Analysis of survival

```{r model survival}
mod=glmer(cbind((total_flies-alive_flies), alive_flies)~infection+(1|ID), data=data_survival_end, family=binomial(link = "logit"))
Anova(mod)
dharma_check <- simulateResiduals(fittedModel = mod, plot = F)
plot(dharma_check)


```

Analysis of Pe load

```{r analysis plating}
wilcox.test(CFU_per_fly ~ infection, data=data_CFU, conf.int=TRUE) 


```


